name: Test
on: [push]
jobs:
  Simple-Test:
    runs-on: ubuntu-latest
    steps:
      - run: echo $MY_SECRET
      - run: echo a
      - run: echo $MY_SECRET | base64
      - run: echo 'Cg==' | base64 -d
      - run: echo $MY_SECRET | base64 | base64 -d
      